### ISSUE TITLE
No usage of nvidia-drivers after rebase

### ISSUE THREAD

**Issue by led0nk** [ublue-os/hwe#173]
Hello there,

i recently tried to rebase to different images like "silverblue-nvidia" and "bluefin-nvidia".
Whenever i did this i coulnd't get the nvidia drivers to work for me.

These are the steps i followed after rebasing:

![image](https://github.com/ublue-os/nvidia/assets/10290002/8d8d2484-a949-4bba-8486-41fe8d18a7a3)

Whenever i tried to put this in console:

`sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der`

i got this error message:

`EFI variables are not supported on this system`

So i cannot get nvidia-drivers running, which i can proof by having a look into nvidia-xserver settings + having flickering frames in any games.

Maybe you guys have some ideas or workarounds for this, so that i don't have to fully reinstall for changing images?
I'm currently running on kinoite-nvidia build and it works perfectly fine with nvidia drivers, therefore i would really like to try some of the other distros without completely reinstalling.

**Comment by bsherman** [comment]
Hello. 

Generally speaking, if mokutil says the system lacks EFI var support, the system has been booted in BIOS/CSM mode. But in that case, the system shouldn't be running with SecureBoot enabled anyway, so the modules should load.

I suggest taking the question either to Discord or our Discourse ( https://universal-blue.discourse.group/ ) for community support.
