### ISSUE TITLE
non-nvidia HWE images (asus/surface) failing to get latest tag

### ISSUE THREAD

**Issue by bsherman** [ublue-os/hwe#217]
This is related to recent HWE refactoring. the nvidia latest 550 images ARE getting `latest` tag but not the `main` for `auss` and `surface`

**Comment by keplersj** [comment]
Is this why `silverblue-surface` isn't based on Fedora 41 now, like `silverblue-main` and `silverblue-nvidia`?

**Comment by bsherman** [comment]
Actually, it's because the surface kernel wasn't being built for F41 as it was having issues when we first started F41 testing.

But now, we are looking at options for changing how HWE works since maintenance on these these extra builds has been lacking since our primary downstreams (Bluefin/Aurora/Bazzite) don't use them.
