### ISSUE TITLE
 feat: update image label with actual kernel version

### ISSUE THREAD

**Issue by bsherman** [ublue-os/hwe#220]
Since we use differing kernels from upstream, we should be properly setting the `ostree.linux` label on the image to reflect the actual kernel within the image.

**Comment by bsherman** [comment]
I haven't checked yet, but I think we could add this to `akmods` images as well.

**Comment by KyleGospo** [comment]
While we're at it, version is using date right now, which is fine -- but it would be nice if it also included commit or build number so two builds on the same date have different version strings.

**Comment by bsherman** [comment]
> While we're at it, version is using date right now, which is fine -- but it would be nice if it also included commit or build number so two builds on the same date have different version strings.

that's fine, but lets make that a distinct issue, probably start in main?
