### ISSUE TITLE
[Unable to boot] Asus image unable to boot after the latest upgrade(2024-04-03)

### ISSUE THREAD

**Issue by Tompott** [ublue-os/hwe#223]
The issue only appears on Asus image, but not in the main.

After upgrade, the system won't boot instead of showing three dots:
![IMG_20240403_071717_926](https://github.com/ublue-os/hwe/assets/165408314/8912f3e0-479e-4a21-b0b7-1ff1bb3a78c7)
Press the ESC:
![IMG_20240403_071756_323](https://github.com/ublue-os/hwe/assets/165408314/2ac06ad2-aa2a-4598-8fa9-6ebb1800d76c)
After some loads:
![IMG_20240403_073317_682](https://github.com/ublue-os/hwe/assets/165408314/d14f13b2-de66-47f6-a5c6-703f31176b43)
It turns out to enter the emergency mode
![5062d41c-8ff0-4ade-bcbb-f0859ebea99b](https://github.com/ublue-os/hwe/assets/165408314/14228ec8-8f81-456b-aa44-151ec4c3172e)

The upgrade has included the kernel, kernel modules from Linux on ASUS ROG.
![IMG_20240403_083431_981](https://github.com/ublue-os/hwe/assets/165408314/f0752a77-a929-415b-bb27-afbdf409c5c1)

**Comment by Rubiginosa** [comment]
Getting this on my own system using asus-nvidia

**Comment by Tompott** [comment]
The issue was appeared by upgraded to the kernel 6.8.2-300-rog. As the newer version 6.8.2-666-rog released, the issue fixed. Therefore the issue will be closed.
