### ISSUE TITLE
Suggestion: Include supergfxctl in asus images

### ISSUE THREAD

**Issue by DreamingCuttlefish** [ublue-os/hwe#244]
The asus-linux project recommends in its documentation that users install supergfxctl from their repository when setting up their utilities in order to enable gpu-switching functionality via the system tray icon and cli program. This is important for users to be able to disable the dGPU on intel+nvidia, amd+nvidia, and amd+amd gpu systems to save battery.

This package is not included in uBlue's asus images. I believe it would make sense for it to be included given its potential benefit for users with dual-gpu laptops.

**Comment by jadejr** [comment]
Even though the `rog-control-center` gui still works without it, it does want it to be there, and perhaps other parts of the program wont behave correctly without it.
