### ISSUE TITLE
[Feature Request] Surface Camera Support

### ISSUE THREAD

**Issue by zhjihuang** [ublue-os/hwe#257]
Is it possible to include the libcamera components by default in the surface images? Not all Surface devices have their cameras functional, but this would save those who are able to use their cameras from having to layer the packages.

Links:
https://github.com/linux-surface/linux-surface/wiki/Camera-Support

**Comment by snoweuph** [comment]
need packages are:
- `libcamera`
- `libcamera-tools`
- libcamera-gstreamer`
- `libcamera-ipa`
- `pipewire-plugin-libcamera`

currently layering them to get it working on my Surface Go
