### ISSUE TITLE
Nvidia driver not working for flatpaks

### ISSUE THREAD

**Issue by ManuaL46** [ublue-os/hwe#277]
Hi after the release of the stable version of the nvidia proprietary driver i.e. 560.35.03 and after the flatpak driver also being updated to the correct version, it seems that I can't use the nvidia GPU for anything flatpak related. 

# System Details Report
---

## Report details
- **Date generated:**                              2024-08-24 16:35:38

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Gaming 3 15ACH6
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 5600H with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics
- **Graphics 1:**                                  NVIDIA GeForce RTX™ 3050 Laptop GPU
- **Disk Capacity:**                               1.5 TB

## Software Information:
- **Firmware Version:**                            H3CN32WW(V2.02)
- **OS Name:**                                     Fedora Linux 40.20240822.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.5-200.fc40.x86_64

![image](https://github.com/user-attachments/assets/1c76d972-f399-4131-8d2c-cd1135b49672)

Does anyone have a fix for this I'm so confused as to why this isn't working

**Comment by TXort** [comment]
Same issue on Fedora Silverblue 39, bluefin-dx-nvidia:gts image.

Switch to xorg for a temporary fix until this gets resolved. After it gets resolved, disable updates related to the issue unless you want your system broken every time Nvidia drivers gets an update. For me 5 times this year already.

**Comment by ManuaL46** [comment]
> Switch to xorg for a temporary fix until this gets resolved.

This didn't work for me, the nvidia GPU works fine for system apps it's just flatpaks that don't have access to it for some reason, even though the GPU drivers are the same version. 
Not sure how it is worked for you as I don't think this is wayland issue.

**Comment by ManuaL46** [comment]
Seems like another nvidia and flathub related issue, adding link for future reference.

Closing this, as it's not related to ublue

[Unable to see Nvidia GPU in the lastest update](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/288)

**Comment by ManuaL46** [comment]
Seems like another nvidia and flathub related issue, adding link for future reference.

Closing this, as it's not related to ublue

https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/288
