### ISSUE TITLE
Add NVIDIA open-source GPU kernel module driver support for Bluefin and Aurora

### ISSUE THREAD

**Issue by rashadgasimli** [ublue-os/hwe#279]
Hello.
Starting with v560 drivers, NVIDIA recommends their open-source GPU kernel module drivers on Turning and newer architectures:
https://developer.nvidia.com/blog/nvidia-transitions-fully-towards-open-source-gpu-kernel-modules/

Bazzite has a seperate image for this. Will there be a seperate image or package for Bluefin and Aurora?

Thanks.

**Comment by castrojo** [comment]
Yep, tracking that here: https://github.com/ublue-os/main/issues/634
