### ISSUE TITLE
[BUG] nvidia-open drivers already shipping?

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/hwe#284]
could be a red herring, but on the silverblue-nvidia image, I'm seeing this in `/etc/nvidia/kernel.conf`:

`nvidia-open`

**Comment by bsherman** [comment]
Good catch, that file is technically incorrect, however the driver itself is correct.

See this verification:
```
$ modinfo -l nvidia
NVIDIA
```

The config file is used for dkms or akmods to determine which version of the driver to build, but we are doing things correctly in akmods but not in hwe.

What is happening is we do change from `nvidia-open` to `nvidia` when building the non-open nvidia driver (see: https://github.com/ublue-os/akmods/actions/runs/11301936520/job/31437048406#step:12:1762 ) however, when installing in HWE (or using the HWE `nvidia-install.sh` script) we do not re-run that sed command, which creates the false impression that the wrong driver may be installed.

The negativo17 maintainer address this config file and how to verify the module itself here:  https://negativo17.org/nvidia-proprietary-and-open-source-kernel-modules/


I'll make the change in the `nvidia-install.sh` script to avoid this confusion.

**Comment by bsherman** [comment]
Fixed here in hwe, also in bluefin, and I think bazzite should already be good to go.
