### ISSUE TITLE
[BUG] initramfs changes cause critical nvidia bug to surface on turing, ampere, and maybe pascal

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/hwe#285]
The upstream issue: <https://forums.developer.nvidia.com/t/550-54-14-cannot-create-sg-table-for-nvkmskapimemory-spammed-when-launching-chrome-on-wayland/284775>

The ublue line that is likely causing this to surface: <https://github.com/ublue-os/hwe/blob/main/nvidia-install.sh#L59>

This bug means that chromium-based browsers are unusable on all ublue nvidia images for certain architectures

Layering the ublue akmod without making that initramfs change fixes the issue.

**Comment by bsherman** [comment]
Ok, I've done a bunch of testing and I'm convinced we need this fix.

What @qoijjj  has done here https://github.com/secureblue/secureblue/blob/live/files/scripts/regenerateinitramfs.sh should be what we do in our nvidia build.

**Comment by bsherman** [comment]
I have to double check how we implement, but would be ideal if we can fix this here in the `hwe` repo as part of `nvidia-install.sh` in a way that would also benefit bazzite/bluefin since they use that script... I'd prefer if we didn't have to update all 3 repos to get the fix out.

**Comment by qoijjj** [comment]
@bsherman for reference of others, I believe you meant to link <https://github.com/secureblue/secureblue/blob/live/files/scripts/setearlyloading.sh>

**Comment by bsherman** [comment]
Fixed by #292
