### ISSUE TITLE
No keyboard and mouse on Sufrace Laptop Studio after latest update

### ISSUE THREAD

**Issue by thmichel** [ublue-os/hwe#304]
Hi,

I was running bluefin-surface-nvidia without issues; since one of the latest updates (after 20241218.1) the integrated keyboard and mouse don't work any more. I rebased to bluefin-hwe to test but same result. Booting into 20241218.1 makes keyboard and mouse work again.

Any suggestions what could be the cause?

**Comment by castrojo** [comment]
Please see: https://github.com/ublue-os/bluefin/issues/2051
