### ISSUE TITLE
nvidia-powerd.service failure

### ISSUE THREAD

**Issue by bhh32** [ublue-os/hwe#71]
After rebasing to the Nvidia builds of Lxqt, KDE, and Mate I'm having the nvidia-powerd.service fail for each one of them, which causes the computer to not finish booting. I'm having the issue on a Dell XPS 15 with a Nvidia GTX 1650 as well as a MSI GS66 Stealth with a Nvidia 3060 laptop GPU.

This also happens in muliti-user (terminal) mode.

**Comment by joshua-stone** [comment]
Hey, does this issue persist on your system?

**Comment by EyeCantCU** [comment]
Encountering this on my desktop with an Nvidia RTX 3070

**Comment by bsherman** [comment]
This seems to have been fixed by https://github.com/ublue-os/config/pull/56
